spring:
  application:
    name: order-service
  rabbitmq:
    host: localhost
    queue:
      order-stock:
        name: order-stock
      order-email:
        name: order-email
    exchange:
      name: order-exchange
    routing-key:
        name: order-routing-key
