spring:
  application:
    name: order-service
  rabbitmq:
    host: localhost
    queue:
      order-stock:
        name: order-stock
      order-email:
        name: order-email
    exchange:
      name: order-exchange
    routing-key:
      stock:
        name: stock-routing-key
      email:
        name: email-routing-key
